BackendBundle\Entity\Tasks:
    type: entity
    table: tasks
    indexes:
        IDX_50586597A76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createdAt:
            type: date
            nullable: true
            column: created_at
        updatedAt:
            type: date
            nullable: true
            column: updated_at
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
